spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "guest"
    password: "guest"
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
